export const EVENTS = {
  LEVEL_FAIL: 'LEVEL_FAIL',
  LEVEL_COMPLETED: 'LEVEL_COMPLETED',
  GAME_OVER: 'GAME_OVER',
  BATTERY_UPGRADE_SML: 'BATTERY_UPGRADE_SML',
  BATTERY_UPGRADE_MED: 'BATTERY_UPGRADE_MED',
  BATTERY_UPGRADE_LRG: 'BATTERY_UPGRADE_LRG',
};

export const BATTERY_LIFE = 30 * 1000 // seconds


export const BATTERY_STATES = {
  HIGH: 'healthy',
  MEDIUM: 'not-so-great',
  LOW: 'critical',
}
