export const EVENTS = {
  LEVEL_FAIL: 'LEVEL_FAIL',
  LEVEL_COMPLETED: 'LEVEL_COMPLETED',
  BATTERY_UPGRADE_SML: 'BATTERY_UPGRADE_SML',
  BATTERY_UPGRADE_MED: 'BATTERY_UPGRADE_MED',
  BATTERY_UPGRADE_LRG: 'BATTERY_UPGRADE_LRG',
  RETRY: 'RETRY'
};
